name: campuslost
description: Aplikasi Pelaporan & Pencarian Barang Hilang di Lingkungan Kampus
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cloud_firestore: ^6.5.0
  firebase_auth: ^6.5.2
  firebase_core: ^4.10.0
  firebase_storage: ^13.4.2
  flutter:
    sdk: flutter
  flutter_map: ^8.3.0
  geolocator: ^14.0.2
  google_fonts: ^6.1.0
  image_picker: ^1.2.2
  intl: ^0.20.2
  latlong2: ^0.9.1
  lottie: ^3.3.3
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_logo.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"